
import React, { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowLeft, faDownload, faHeart, faComment, faShareAlt, faCheckCircle, faFileAlt, faFilePdf, faFileWord, faChevronDown } from '@fortawesome/free-solid-svg-icons';
import { DesignBrief, User } from '../types';
import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

interface BriefDetailProps {
  challenges: DesignBrief[];
  currentUser: User | null;
}

const BriefDetail: React.FC<BriefDetailProps> = ({ challenges, currentUser }) => {
  const { id } = useParams<{ id: string }>();
  const [showSubmissionForm, setShowSubmissionForm] = useState(false);
  const [liked, setLiked] = useState(false);
  const challenge = challenges.find(c => c.id === id);

  if (!challenge) {
    return (
      <div className="p-20 text-center dark:text-white flex flex-col items-center justify-center min-h-screen">
        <h2 className="text-3xl font-black mb-4">Brief Not Found</h2>
        <Link to="/challenges" className="text-indigo-600 font-bold hover:underline">Return to Arena</Link>
      </div>
    );
  }

  const [showDownloadMenu, setShowDownloadMenu] = useState(false);

  const downloadAsTxt = () => {
    const content = `
DESIGN BRIEF: ${challenge.title}
Category: ${challenge.category}
Difficulty: ${challenge.difficulty}

DESCRIPTION:
${challenge.description}

KEY DELIVERABLES:
${challenge.deliverables.map((d, i) => `${i + 1}. ${d}`).join('\n')}

RECOMMENDED TOOLS:
${challenge.tools.join(', ')}

Generated by Designa-rs
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    saveAs(blob, `${challenge.title.replace(/\s+/g, '_')}_Brief.txt`);
    setShowDownloadMenu(false);
  };

  const downloadAsPdf = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(`DESIGN BRIEF: ${challenge.title}`, margin, y);
    y += 15;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Category: ${challenge.category}`, margin, y);
    y += 7;
    doc.text(`Difficulty: ${challenge.difficulty}`, margin, y);
    y += 7;
    y += 8;

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('DESCRIPTION:', margin, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const splitDescription = doc.splitTextToSize(challenge.description, 170);
    doc.text(splitDescription, margin, y);
    y += (splitDescription.length * 7) + 10;

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('KEY DELIVERABLES:', margin, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    challenge.deliverables.forEach((d, i) => {
      doc.text(`${i + 1}. ${d}`, margin, y);
      y += 7;
    });
    y += 10;

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('RECOMMENDED TOOLS:', margin, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(challenge.tools.join(', '), margin, y);
    
    doc.save(`${challenge.title.replace(/\s+/g, '_')}_Brief.pdf`);
    setShowDownloadMenu(false);
  };

  const downloadAsWord = async () => {
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: `DESIGN BRIEF: ${challenge.title}`,
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Category: ${challenge.category}`, bold: true }),
              new TextRun({ text: `\nDifficulty: ${challenge.difficulty}`, bold: true }),
            ],
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            text: "DESCRIPTION",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({
            text: challenge.description,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            text: "KEY DELIVERABLES",
            heading: HeadingLevel.HEADING_2,
          }),
          ...challenge.deliverables.map((d, i) => new Paragraph({
            text: `${i + 1}. ${d}`,
            bullet: { level: 0 }
          })),
          new Paragraph({ text: "" }),
          new Paragraph({
            text: "RECOMMENDED TOOLS",
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({
            text: challenge.tools.join(', '),
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            text: "Generated by Designa-rs",
            alignment: AlignmentType.RIGHT,
          }),
        ],
      }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `${challenge.title.replace(/\s+/g, '_')}_Brief.docx`);
    setShowDownloadMenu(false);
  };

  return (
    <div className="py-12 bg-slate-50 dark:bg-slate-950 transition-colors duration-300">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link to="/challenges" className="inline-flex items-center text-slate-500 dark:text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 mb-8 transition-colors font-bold text-sm uppercase tracking-wider">
          <FontAwesomeIcon icon={faArrowLeft} className="mr-2" />
          Back to Challenges
        </Link>

        <div className="bg-white dark:bg-slate-900 rounded-[3rem] overflow-hidden border border-slate-200 dark:border-slate-800 shadow-xl shadow-slate-200/50 dark:shadow-none transition-colors">
          <div className="aspect-[21/9] md:aspect-[21/9] aspect-[16/10] w-full relative">
            <img src={challenge.image} alt={challenge.title} className="w-full h-full object-cover" />
            <div className="absolute inset-0 bg-gradient-to-t from-slate-900/90 via-slate-900/20 to-transparent flex items-end p-6 md:p-12">
              <div>
                <div className="flex flex-wrap gap-2 md:gap-4 mb-4">
                  <span className="bg-white text-slate-900 px-3 md:px-4 py-1.5 rounded-full text-[8px] md:text-[10px] font-black uppercase tracking-widest">{challenge.category}</span>
                  <span className="bg-indigo-600 text-white px-3 md:px-4 py-1.5 rounded-full text-[8px] md:text-[10px] font-black uppercase tracking-widest">{challenge.difficulty}</span>
                </div>
                <h1 className="text-3xl md:text-5xl font-black text-white mb-6 leading-tight">{challenge.title}</h1>
                
                <div className="flex flex-wrap items-center gap-4 md:gap-6">
                  <button 
                    onClick={() => setLiked(!liked)}
                    className={`flex items-center space-x-2 text-xs md:text-sm font-black transition-colors ${liked ? 'text-rose-500' : 'text-white/70 hover:text-rose-500'}`}
                  >
                    <FontAwesomeIcon icon={faHeart} />
                    <span>{liked ? (challenge.likes || 0) + 1 : (challenge.likes || 0)} Likes</span>
                  </button>
                  <button className="flex items-center space-x-2 text-xs md:text-sm font-black text-white/70 hover:text-indigo-400 transition-colors">
                    <FontAwesomeIcon icon={faComment} />
                    <span>{challenge.commentsCount || 0} Comments</span>
                  </button>
                  <button className="flex items-center space-x-2 text-xs md:text-sm font-black text-white/70 hover:text-indigo-400 transition-colors">
                    <FontAwesomeIcon icon={faShareAlt} />
                    <span>Share</span>
                  </button>
                </div>
              </div>
            </div>
          </div>

          <div className="p-8 md:p-16">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-16">
              <div className="lg:col-span-2">
                <section className="mb-12">
                  <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6 flex items-center">
                    <span className="w-1.5 h-8 bg-indigo-600 rounded-full mr-4"></span>
                    The Brief
                  </h2>
                  <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-lg whitespace-pre-line">
                    {challenge.description}
                  </p>
                </section>

                <section className="mb-12">
                  <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-6 flex items-center">
                    <span className="w-1.5 h-8 bg-indigo-600 rounded-full mr-4"></span>
                    Key Deliverables
                  </h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {challenge.deliverables.map((item, idx) => (
                      <div key={idx} className="flex items-center p-4 bg-slate-50 dark:bg-slate-950 rounded-2xl border border-slate-100 dark:border-slate-800">
                        <div className="w-8 h-8 rounded-xl bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-sm font-black mr-4 shadow-sm">
                          {idx + 1}
                        </div>
                        <span className="text-slate-600 dark:text-slate-400 font-bold text-sm">{item}</span>
                      </div>
                    ))}
                  </div>
                </section>
              </div>

              <div className="space-y-10">
                <div>
                  <h3 className="font-black text-slate-900 dark:text-white mb-6 uppercase tracking-widest text-xs ml-1">Stack Recommendation</h3>
                  <div className="flex flex-wrap gap-2">
                    {challenge.tools.map(tool => (
                      <span key={tool} className="bg-white dark:bg-slate-800 px-5 py-3 rounded-2xl border border-slate-200 dark:border-slate-700 text-xs font-black text-slate-600 dark:text-slate-300 shadow-sm transition-all hover:border-indigo-600">
                        {tool}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="pt-6 space-y-4 relative">
                  <div className="relative">
                    <button 
                      onClick={() => setShowDownloadMenu(!showDownloadMenu)}
                      className="w-full bg-indigo-600 text-white py-6 rounded-[2rem] font-black text-lg shadow-2xl shadow-indigo-200 dark:shadow-indigo-900/20 hover:bg-indigo-700 hover:-translate-y-1 transition-all flex items-center justify-center space-x-3"
                    >
                      <span>Download Brief</span>
                      <FontAwesomeIcon icon={faDownload} />
                      <FontAwesomeIcon icon={faChevronDown} className={`text-xs transition-transform ${showDownloadMenu ? 'rotate-180' : ''}`} />
                    </button>

                    {showDownloadMenu && (
                      <div className="absolute top-full left-0 right-0 mt-4 bg-white dark:bg-slate-800 rounded-3xl shadow-2xl border border-slate-100 dark:border-slate-700 overflow-hidden z-50 animate-in fade-in slide-in-from-top-2 duration-200">
                        <button 
                          onClick={downloadAsTxt}
                          className="w-full flex items-center space-x-4 px-8 py-5 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors text-left border-b border-slate-100 dark:border-slate-700"
                        >
                          <div className="w-10 h-10 rounded-xl bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 flex items-center justify-center">
                            <FontAwesomeIcon icon={faFileAlt} />
                          </div>
                          <div>
                            <div className="font-black text-slate-900 dark:text-white text-sm">Text Document</div>
                            <div className="text-[10px] text-slate-400 font-bold uppercase">.TXT Format</div>
                          </div>
                        </button>
                        <button 
                          onClick={downloadAsPdf}
                          className="w-full flex items-center space-x-4 px-8 py-5 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors text-left border-b border-slate-100 dark:border-slate-700"
                        >
                          <div className="w-10 h-10 rounded-xl bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400 flex items-center justify-center">
                            <FontAwesomeIcon icon={faFilePdf} />
                          </div>
                          <div>
                            <div className="font-black text-slate-900 dark:text-white text-sm">PDF Document</div>
                            <div className="text-[10px] text-slate-400 font-bold uppercase">.PDF Format</div>
                          </div>
                        </button>
                        <button 
                          onClick={downloadAsWord}
                          className="w-full flex items-center space-x-4 px-8 py-5 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors text-left"
                        >
                          <div className="w-10 h-10 rounded-xl bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 flex items-center justify-center">
                            <FontAwesomeIcon icon={faFileWord} />
                          </div>
                          <div>
                            <div className="font-black text-slate-900 dark:text-white text-sm">Word Document</div>
                            <div className="text-[10px] text-slate-400 font-bold uppercase">.DOCX Format</div>
                          </div>
                        </button>
                      </div>
                    )}
                  </div>
                  
                  <p className="text-center text-[10px] font-black uppercase tracking-widest text-slate-400">
                    Choose your preferred format to start designing
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BriefDetail;
